"""empty message

Revision ID: 306c8989129d
Revises: 95369b900588
Create Date: 2020-05-29 23:16:13.769698

"""

# revision identifiers, used by Alembic.
revision = '306c8989129d'
down_revision = '95369b900588'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('categories', sa.String(length=255), nullable=True),
    sa.Column('public', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
