"""empty message

Revision ID: 3e6bc5454dbf
Revises: None
Create Date: 2020-05-30 00:57:03.798248

"""

# revision identifiers, used by Alembic.
revision = '3e6bc5454dbf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'file_name')
    # ### end Alembic commands ###
