"""empty message

Revision ID: 6cbbf977a910
Revises: None
Create Date: 2020-05-29 21:20:52.705447

"""

# revision identifiers, used by Alembic.
revision = '6cbbf977a910'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
